### ISSUE TITLE
当画面比例不是16:9时，左右画面会有黑边

### ISSUE THREAD

**Issue by CC-3301** [paulzzh/YuZuUI-GTNH#1]
如题
![image](https://github.com/user-attachments/assets/d1062583-a7c7-4828-96ab-9c99b1ed5ee4)

**Comment by CC-3301** [comment]
人物的图像也有锯齿，应该是图片资源分辨率不够高，这个用waifu2x处理一下不知道可不可行

**Comment by paulzzh** [comment]
参考 https://www.bilibili.com/video/BV1PRy2YZEmx
左右或者上下的黑边应该是故意设计的，上游项目也是这样
虚拟分辨率只有1920x1080，以此建立相对的组件坐标关系，固定16:9，多余部分填充黑边

**Comment by CC-3301** [comment]
好的 上游也是这样那就没办法了

**Comment by paulzzh** [comment]
> 人物的图像也有锯齿，应该是图片资源分辨率不够高，这个用waifu2x处理一下不知道可不可行

可尝试更新 https://github.com/paulzzh/YuZuUI-GTNH/releases/tag/1.0.5

**Comment by CC-3301** [comment]
> > 人物的图像也有锯齿，应该是图片资源分辨率不够高，这个用waifu2x处理一下不知道可不可行
> 
> 可尝试更新 https://github.com/paulzzh/YuZuUI-GTNH/releases/tag/1.0.5

锯齿没有了，感谢开发者
![image](https://github.com/user-attachments/assets/da7dae46-686d-4a3c-a0f7-c2a5d6e57fb9)

**Comment by CC-3301** [comment]
不过更新后，左边UI有点瑕疵，通过切换对比这个issue我发的两张图可以察觉到
![image](https://github.com/user-attachments/assets/9504a127-1d9e-41e1-aa38-164af3eed7cd)

**Comment by CC-3301** [comment]
> 不过更新后，左边UI有点瑕疵，通过切换对比这个issue我发的两张图可以察觉到 ![image](https://private-user-images.githubusercontent.com/38343280/399134830-9504a127-1d9e-41e1-aa38-164af3eed7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NDIxMDMsIm5iZiI6MTczNTQ0MTgwMywicGF0aCI6Ii8zODM0MzI4MC8zOTkxMzQ4MzAtOTUwNGExMjctMWQ5ZS00MWUxLWFhMzgtMTY0YWYzZWVkN2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDAzMTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OTM3YWNiZjkwZjc2YmIyNDBjM2QwZDFkNmI3N2ZhMzQzYjY4OWQxYWIzZTg0ZmM5NzBkODAzOWI1N2Y0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-9y2HyXTj6QCDi2beMRXgpDSJ6dOTviuqpi_qsAQ-7o)

奇怪的是 在窗口分辨率为1920x1080下就没问题 一旦窗口最大化 比例不是16:9了就会出现

**Comment by CC-3301** [comment]
还有个问题，从存档退回到主页面后，语音播报会变成单声道

**Comment by paulzzh** [comment]
> 还有个问题，从存档退回到主页面后，语音播报会变成单声道

https://github.com/paulzzh/YuZuUI-GTNH/actions/runs/12533937701/artifacts/2369011767
无法复现，但是尝试修了一下，可以看看这个版本还有没有贴图瑕疵和语音的问题

**Comment by CC-3301** [comment]
> > 还有个问题，从存档退回到主页面后，语音播报会变成单声道
> 
> https://github.com/paulzzh/YuZuUI-GTNH/actions/runs/12533937701/artifacts/2369011767 无法复现，但是尝试修了一下，可以看看这个版本还有没有贴图瑕疵和语音的问题

贴图瑕疵的问题修复了，但语音的问题依旧，表现为：从单人存档退出到主界面后，点击后日谈、系统设置等按钮，语音播报会变成随机左/右的单声道，而且这个版本引入了一个新BUG，点击鉴赏模式会报错
![image](https://github.com/user-attachments/assets/afd4027e-1d87-4ca2-85eb-58b9236072db)
具体日志我放在了：https://netcut.cn/1ig8pn3ed

**Comment by paulzzh** [comment]
> 而且这个版本引入了一个新BUG，点击鉴赏模式会报错

不太像是这两天的提交能搞出的bug，可点击退出后返回原始菜单，看看点击原菜单的模组列表按钮是不是仍然报错

**Comment by CC-3301** [comment]
> > 而且这个版本引入了一个新BUG，点击鉴赏模式会报错
> 
> 不太像是这两天的提交能搞出的bug，可点击退出后返回原始菜单，看看点击原菜单的模组列表按钮是不是仍然报错

我重启之后无论怎么点击鉴赏模式都不报错了，奇妙

**Comment by CC-3301** [comment]
噢原来不是单声道 是双声道音量不平衡

**Comment by paulzzh** [comment]
> > > 而且这个版本引入了一个新BUG，点击鉴赏模式会报错
> > 
> > 
> > 不太像是这两天的提交能搞出的bug，可点击退出后返回原始菜单，看看点击原菜单的模组列表按钮是不是仍然报错
> 
> 我重启之后无论怎么点击鉴赏模式都不报错了，奇妙

估计是什么NEI之类的自己抽风，
语音的问题，感觉好像有一个耳朵的语音声音会特别小？你遇到的是这个问题吗

**Comment by CC-3301** [comment]
> > > > 而且这个版本引入了一个新BUG，点击鉴赏模式会报错
> > > 
> > > 
> > > 不太像是这两天的提交能搞出的bug，可点击退出后返回原始菜单，看看点击原菜单的模组列表按钮是不是仍然报错
> > 
> > 
> > 我重启之后无论怎么点击鉴赏模式都不报错了，奇妙
> 
> 估计是什么NEI之类的自己抽风， 语音的问题，感觉好像有一个耳朵的语音声音会特别小？你遇到的是这个问题吗

是的

**Comment by CC-3301** [comment]
而且这个问题只发生在从单人模式的存档里面退出，如果从服务器退出到主界面就没问题

**Comment by paulzzh** [comment]
> 而且这个问题只发生在从单人模式的存档里面退出，如果从服务器退出到主界面就没问题

尝试 https://github.com/paulzzh/YuZuUI-GTNH/actions/runs/12534377165 ，等ci跑完

**Comment by CC-3301** [comment]
> > 而且这个问题只发生在从单人模式的存档里面退出，如果从服务器退出到主界面就没问题
> 
> 尝试 https://github.com/paulzzh/YuZuUI-GTNH/actions/runs/12534377165 ，等ci跑完

fix

**Comment by paulzzh** [comment]
上游项目挖的坑疑似有点多了。。
贴图带一堆噪点，音乐格式是双声道，语音格式是单声道

**Comment by RuiXuqi** [comment]
> 上游项目挖的坑疑似有点多了。。 贴图带一堆噪点，音乐格式是双声道，语音格式是单声道

想请教一下，单声道转双声道用的是什么工具，我这边新加的人物语音全是单声道的，不知道怎么转（

**Comment by paulzzh** [comment]
> 想请教一下，单声道转双声道用的是什么工具，我这边新加的人物语音全是单声道的，不知道怎么转（

查一下 ffmpeg mono to stereo 的命令

**Comment by RuiXuqi** [comment]
> > 想请教一下，单声道转双声道用的是什么工具，我这边新加的人物语音全是单声道的，不知道怎么转（
> 
> 查一下 ffmpeg mono to stereo 的命令

改好了，十分感谢:)

**Comment by RuiXuqi** [comment]
> > 想请教一下，单声道转双声道用的是什么工具，我这边新加的人物语音全是单声道的，不知道怎么转（
> 
> 查一下 ffmpeg mono to stereo 的命令

改好了，十分感谢:)
